---
# Playbook pull the MikroTik Router Config File
   - hosts: mikrotik
     gather_facts: no
     tasks:
       - name: SSH into MikroTik router and export configuration
         ansible.builtin.command:
         path: "/system/export"
         output: "mikrotik_config.rsc"
         register: config_export 

       - name: Save configuration to file
         delegate_to: localhost
         file:
           path: "/home/scott/backups//{{ inventory_hostname }}_config.rsc"
           content: "{{ config_export.result }}"
           mode: '0644'          

#       - name: Fetch the exported file from MikroTik router
#         ansible.builtin.fetch:
#           src: /system/export/mikrotik_config.rsc
#           dest: /home/scott/backups/{{hostvars.localhost.DTG}}/{{inventory_hostname}}-{{hostvars.localhost.DTG}}-config.txt
#           flat: yes
#         when: export_output.rc == 0

