---
# Playbook pull the MikroTik Router Config File
- hosts: Mikrotik
  gather_facts: false
  
  tasks:
    - name: Backup Mikrotik configs
      routeros_command:
        commands: /export
      register: config

    - name: Save output to config-backups
      copy:
        content: "{{config.stdout[0]}}"
        dest: "{/home/scott/config-backup/{{inventory_hostname}}-config.txt"
