---
# Playbook pull the MikroTik Router Config File
- hosts: mikrotik
  gather_facts: false
  
  tasks:
    - name: Backup Mikrotik configs
      routeros_command:
        commands: /export file=config
      register: config

    - name: Save output to config-backups
      copy:
        content: config
        dest: /home/scott/backups/mikrotik-config.txt
